"""Plotting functions for Lissajous curves and related shapes."""

import math

import numpy as np
import matplotlib.pyplot as plt


def circle_polyline(delta: int) -> tuple[np.ndarray, np.ndarray]:
    """Generate x and y coordinates for a circle polyline.

    A circle is a special case of a Lissajous curve with fx = fy = 1.

    Args:
        delta (int): Positive integer less than 360

    Returns:
        tuple[np.ndarray, np.ndarray]: Arrays of x and y coordinates for n points

    Raises:
        ValueError: If delta is invalid (see angle_list for requirements)
    """
    return lissajou_polyline(1, 1, delta)


def lissajou_polyline(fx: int, fy: int, delta: int) -> tuple[np.ndarray, np.ndarray]:
    """Generate x and y coordinates for a Lissajous curve polyline.

    The Lissajous curve is computed using parametric equations:
    x = cos(fx * t), y = sin(fy * t)
    where t is generated by angle_list(delta), and fx, fy are the frequencies.

    Args:
        fx (int): Frequency for x coordinate (positive integer)
        fy (int): Frequency for y coordinate (positive integer)
        delta (int): Positive integer less than 360

    Returns:
        tuple[np.ndarray, np.ndarray]: Arrays of x and y coordinates for n points

    Raises:
        ValueError: If fx or fy is not positive
        ValueError: If delta is invalid (see angle_list for requirements)
    """
    if fx <= 0:
        raise ValueError("fx must be positive")
    if fy <= 0:
        raise ValueError("fy must be positive")

    # Generate angles
    angles: list[int] = angle_list(delta)

    # Convert degrees to radians
    t: np.ndarray = np.array(angles) * np.pi / 180

    # Compute x and y coordinates with frequencies
    x: np.ndarray = 3 * np.cos(fx * t)
    y: np.ndarray = 2 * np.sin(fy * t)

    return x, y


def plot_polyline(x: np.ndarray, y: np.ndarray, title: str = "Polyline") -> None:
    """Plot a polyline given x and y coordinate arrays.

    The polyline is closed by appending the first point to the end before plotting.

    Args:
        x (np.ndarray): Array of x coordinates
        y (np.ndarray): Array of y coordinates
        title (str): Title for the plot (default: "Polyline")
    """
    # Close the polyline by appending the first point to the end
    x_closed: np.ndarray = np.append(x, x[0])
    y_closed: np.ndarray = np.append(y, y[0])

    plt.figure(figsize=(6, 6))
    plt.plot(x_closed, y_closed, 'b-', linewidth=1)
    plt.axis('equal')
    plt.grid(True, alpha=0.3)
    plt.title(title)
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()


def plot_circle(delta: int) -> None:
    """Plot a circle by drawing lines between points at angles determined by delta.

    A circle is a special case of a Lissajous curve with fx = fy = 1.

    Args:
        delta (int): Positive integer less than 360

    Raises:
        ValueError: If delta is invalid (see angle_list for requirements)
    """
    plot_lissajou(1, 1, delta)


def plot_lissajou(fx: int, fy: int, delta: int) -> None:
    """Plot a Lissajous curve by drawing lines between points.

    The Lissajous curve is computed using parametric equations:
    x = cos(fx * t), y = sin(fy * t)
    where t is generated by angle_list(delta), and fx, fy are the frequencies.

    Args:
        fx (int): Frequency for x coordinate (positive integer)
        fy (int): Frequency for y coordinate (positive integer)
        delta (int): Positive integer less than 360

    Raises:
        ValueError: If fx, fy, or delta is invalid
    """
    x: np.ndarray
    y: np.ndarray
    x, y = lissajou_polyline(fx, fy, delta)
    assert len(x) == len(y), "x and y arrays must have the same length"
    n: int = len(x)
    plot_polyline(x, y, title=f'Lissajous fx={fx}, fy={fy}, delta={delta}, n={n}')


def angle_list(delta: int) -> list[int]:
    """Generate a list of n angles in range(360).

    The number of angles n is computed as n = 360 / gcd(delta, 360).
    Each angle i in the list is computed as (delta * i) % 360 for i in range(n).

    Args:
        delta (int): Positive integer less than 360

    Returns:
        list[int]: List of n angles where angle[i] = (delta * i) % 360

    Raises:
        ValueError: If delta is not positive or >= 360
    """
    if delta <= 0:
        raise ValueError("delta must be positive")
    if delta >= 360:
        raise ValueError("delta must be less than 360")

    m: int = math.gcd(delta, 360)
    n: int = 360 // m
    angles: list[int] = [(delta * i) % 360 for i in range(n)]
    return angles


if __name__ == "__main__":
    plot_lissajou(1, 2, 113)
